services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_PLATFORM=linux/amd64
    platform: linux/amd64
    image: safeguardx
    container_name: safeguardx
    volumes:
      - .:/var/www
    depends_on:
      - vite
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite

  nginx:
    image: nginx:1.26-alpine
    platform: linux/amd64
    container_name: safeguardx_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  vite:
    image: node:18.20.4
    platform: linux/amd64
    container_name: safeguardx_vite
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"